#!/bin/bash
#
# generate-images
# jms1 2023-07-09
# Last updated 2024-10-20
#
# - Run the script to generate the template images
# - Create small versions of each image, to show in the README.md file

set -ex

###############################################################################
#
# Create a small version of an image

function make_small {
    FILE="$1"
    FILE_SM="${FILE%.png}-sm.png"

    WORK="$( mktemp )"

    ########################################
    # Create a small version of the image

    cp "$FILE" "$WORK"
    mogrify -scale 20% "$WORK"

    ########################################
    # Add a black 1px border to the small image

    magick "$WORK" \
        -background black \
        -gravity northwest -splice 1x1 \
        -gravity southeast -splice 1x1 \
        "$FILE_SM"

    rm -f "$WORK"
}

###############################################################################
###############################################################################
###############################################################################

mkdir -p rm12 rmpp

./rm2-template-calendar    -Ll -o rm12/L-CalendarMo-lh.png
./rm2-template-calendar    -Lr -o rm12/L-CalendarMo-rh.png
./rm2-template-calendar    -Pl -o rm12/P-CalendarMo-lh.png
./rm2-template-calendar    -Pr -o rm12/P-CalendarMo-rh.png

./rm2-template-calendar -p -Ll -o rmpp/L-CalendarMo-lh.png
./rm2-template-calendar -p -Lr -o rmpp/L-CalendarMo-rh.png
./rm2-template-calendar -p -Pl -o rmpp/P-CalendarMo-lh.png
./rm2-template-calendar -p -Pr -o rmpp/P-CalendarMo-rh.png

make_small rm12/L-CalendarMo-lh.png
make_small rm12/L-CalendarMo-rh.png
make_small rm12/P-CalendarMo-lh.png
make_small rm12/P-CalendarMo-rh.png

make_small rmpp/L-CalendarMo-lh.png
make_small rmpp/L-CalendarMo-rh.png
make_small rmpp/P-CalendarMo-lh.png
make_small rmpp/P-CalendarMo-rh.png
