#!/bin/bash
#
# generate-images
# jms1 2023-07-09
#
# - Run the script to generate the template images
# - Create small versions of each image, to show in the README.md file

set -ex

###############################################################################
#
# Create a small version of an image

function make_small {
    FILE="$1"
    FILE_SM="${FILE%.png}-sm.png"

    WORK="$( mktemp )"

    ########################################
    # Create a small version of the image

    cp "$FILE" "$WORK"
    mogrify -scale 20% "$WORK"

    ########################################
    # Add a black 1px border to the small image

    magick "$WORK" \
        -background black \
        -gravity northwest -splice 1x1 \
        -gravity southeast -splice 1x1 \
        "$FILE_SM"

    rm -f "$WORK"
}

###############################################################################
###############################################################################
###############################################################################

rm -rf rm12 rmpp
mkdir rm12 rmpp

./rm2-template-basic -D rm12        -P -r
./rm2-template-basic -D rm12        -P -l
./rm2-template-basic -D rm12        -L -r
./rm2-template-basic -D rm12        -L -l

./rm2-template-basic -D rmpp -p -d58 -P -r
./rm2-template-basic -D rmpp -p -d58 -P -l
./rm2-template-basic -D rmpp -p -d58 -L -r
./rm2-template-basic -D rmpp -p -d58 -L -l

for PRE in rm12/P rm12/L rmpp/P rmpp/L
do
    make_small "${PRE}-dots-only.png"

    for SUF in rh lh
    do
        make_small "${PRE}-basic-page-${SUF}.png"
        make_small "${PRE}-daily-work-${SUF}.png"
    done
done
